apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
    spec:
      containers:
        - name: node-app1
          image: docker-image-app1
          ports:
            - containerPort: 3000
