apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
    spec:
      containers:
        - name: node-app1
          image: node:14  # Example: Use Node.js image directly
          command: ["node"]
          args: ["app.js"]  # Command to run the application
          ports:
            - containerPort: 3000
