name: Deploy EKS Cluster and Applications

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0  # Specify your Terraform version

      - name: Navigate to Terraform directory
        run: cd terraform/

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Deploy App 1 to EKS
        run: kubectl apply -f applications/app1/deployment.yaml

      - name: Deploy App 2 to EKS
        run: kubectl apply -f applications/app2/deployment.yaml
